"""add currency column

Revision ID: e509e994dba3
Revises: 0b5cc44f4a90
Create Date: 2020-03-23 08:15:34.238313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e509e994dba3'
down_revision = '0b5cc44f4a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candle', sa.Column('candle_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candle', 'candle_currency')
    # ### end Alembic commands ###
